### ISSUE TITLE
Redundant-ish services with unreachable endpoints

### ISSUE THREAD

**Issue by paweljur** [niewiemmichal/UnderHisEye#16]
Assistants, doctors, registrants, supervisors and users services are unnecessarily specific with similiar functionality. Furthermore all of the endpoints which refer to users by id are impossible to be used, because it seems there's no way to retrived needed id (User object does not contain one).

Solution:
- common data should be included as one User object, that is id, name, surname, role, username  and gmcnumber
- add endpoint to users service which for retrieving users by id

Minor remark: services should be name as singular and not plural

**Comment by Sh1ftry** [comment]
Added endpoint to retrieve staff details by username
