### ISSUE TITLE
Design state machine for visit and laboratory tests

### ISSUE THREAD

**Issue by Sh1ftry** [niewiemmichal/UnderHisEye#2]
Visit and laboratory tests have some states, so to properly implement it, we need a state machine.

**Comment by nnauka** [comment]
![IMG_20190412_155802](https://user-images.githubusercontent.com/22588169/56042866-4cd59f00-5d3c-11e9-8cf9-3ba1918445a1.jpg)
![IMG_20190412_155825](https://user-images.githubusercontent.com/22588169/56042886-55c67080-5d3c-11e9-99ba-96d64cf47114.jpg)

Pretty much just rewritten state machine from source materials provided by the client.
